import React from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import "./landing.css";
import "./landing-scale.css";

const features = [["▤", "Manage Applications", "Keep track of all your job and internship applications easily."], ["▥", "Track Companies", "Save your dream companies and never miss an opportunity."], ["◫", "Prepare for Interviews", "Organize interview dates, notes, and resources."], ["▥", "Get Insights", "Visualize your progress with beautiful analytics."]];
const steps = [["1", "◉", "Create an Account", "Sign up in seconds and set up your profile."], ["2", "+", "Add Applications", "Track the jobs and internships you apply to."], ["3", "▥", "Monitor Progress", "See your status and get insights."], ["4", "★", "Achieve Your Goals", "Stay consistent and land your dream job."]];

export default function Landing() {
  const { user } = useAuth(); const start = user ? "/dashboard" : "/register";
  return <div className="new-home"><header className="home-nav"><Link className="home-logo" to="/"><span>◆</span> Placement<strong>Track</strong></Link><nav><a className="selected" href="#home">Home</a><a href="#features">Features</a><a href="#how-it-works">How It Works</a><a href="#testimonials">Testimonials</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div className="nav-actions"><Link to="/login">Login</Link><Link className="primary-btn mini" to={start}>Sign Up</Link></div></header>
    <main id="home"><section className="new-hero"><div className="hero-copy"><p className="hero-pill">↗ &nbsp; Plan&nbsp; Track&nbsp; Prepare&nbsp; Succeed</p><h1>Track Your<br />Placement Journey.<br /><span>Get Hired.</span></h1><p className="hero-description">Manage your job and internship applications, track progress, prepare for interviews, and achieve your dream career — all in one place.</p><div className="hero-buttons"><Link className="primary-btn" to={start}>Get Started Free&nbsp; →</Link><button className="watch-btn">▶ <span>Watch Demo</span></button></div><p className="trusted"><b>◉ ◉ ◉ ◉</b> Trusted by 10,000+ students<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;across 500+ colleges</p></div><div className="hero-art"><div className="scribble top-note">Same<br />Student<br />Bigger<br />Opportunities!</div><div className="portrait-wrap"><img src="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=90" alt="Temporary student placeholder — replace this image later" /></div><div className="scribble bottom-note">Track<br />Prepare<br />Get Hired!</div></div></section>
    <section id="features" className="feature-grid">{features.map(([icon,title,text], index)=><article key={title}><i className={`feature-icon tone-${index}`}>{icon}</i><h3>{title}</h3><p>{text}</p></article>)}</section>
    <section id="how-it-works" className="steps"><p className="section-tag">✦ HOW IT WORKS</p><h2>Simple Steps to a Brighter Future</h2><p>Get started in minutes and take control of your placement journey.</p><div className="step-list">{steps.map(([number,icon,title,text])=><article key={number}><span className="step-number">{number}</span><i>{icon}</i><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="testimonials" className="testimonials"><h2>Trusted by Students Like You</h2><p>Real stories from real students who used PlacementTrack to achieve their goals.</p><div className="testimonial-grid">{[["Aditi Sharma","Final Year, CSE","PlacementTrack made my placement journey so much easier. I could track everything in one place!"],["Rahul Mehta","Pre-Final Year, IT","The analytics and reminders are amazing. It really keeps me motivated to apply and stay consistent."],["Neha Kapoor","Final Year, ECE","I love how simple and helpful PlacementTrack is. A must-have for every student!"]].map((item,index)=><article key={item[0]}><div className="quote-avatar">{item[0][0]}</div><p>“{item[2]}”</p><b>★★★★★</b><h4>{item[0]}</h4><small>{item[1]}</small></article>)}</div></section>
    <section id="pricing" className="closing-banner"><div><h2>Ready to Take Control of Your Future?</h2><p>Join thousands of students who are tracking, applying, and getting hired.</p><Link className="primary-btn" to={start}>Get Started Free &nbsp;→</Link><a href="#features" className="outline-btn">View Features</a></div><div className="banner-note">Your<br />Dream Career<br />Awaits! ↗</div></section></main>
    <footer><div className="footer-brand"><Link className="home-logo" to="/"><span>◆</span> Placement<strong>Track</strong></Link><p>Today. Get Hired Tomorrow.</p></div>{[["Product","Features","Pricing","FAQ"],["Company","About","Blog","Contact"],["Resources","Interview Tips","Career Guide","Student Community"]].map(x=><div className="footer-list" key={x[0]}><b>{x[0]}</b>{x.slice(1).map(item=><a href="#home" key={item}>{item}</a>)}</div>)}<div className="social"><b>Connect With Us</b><p>in &nbsp; ◉ &nbsp; ♥ &nbsp; ▶</p><small>© 2026 PlacementTrack. All rights reserved.</small></div></footer>
  </div>;
}
